services:
    erp_hbr_app:
        build:
            context: .
            dockerfile: docker/app.dockerfile
        container_name: erp.hbr-app
        volumes:
            - .:/var/www/html
        networks:
            - traefik_net
        user: "${UID:-1000}:${GID:-1000}"

    erp_hbr_nginx:
        image: nginx:alpine
        container_name: erp.hbr-nginx
        ports:
            - "8060:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
        networks:
            - traefik_net
        labels:
            - traefik.enable=true
            - traefik.http.routers.erphbr-secure.rule=Host(`erp.hbr.test`)
            - traefik.http.routers.erphbr-secure.tls=true
            - traefik.http.routers.erphbr-secure.entrypoints=websecure
            - traefik.http.services.erphbr-secure.loadbalancer.server.port=80
            - traefik.http.routers.erphbr-web.entrypoints=web
            - traefik.http.routers.erphbr-web.rule=Host(`erp.hbr.test`)
            - traefik.http.routers.erphbr-web.middlewares=redirect-to-https
            - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
networks:
    traefik_net:
        external: true
