[default.extend-words]
# Don't correct the surname "Teh"
Thay = "Thay"
thay = "thay"
Nam = "Nam"
thead = "thead"
theads = "theads"
ue = "ue"
noice = "noice"
ot = "ot"
PHPDoc = "PHPDoc"
gitsigns = "gitsigns"
intelephense = "intelephense"
