M script-binding manager-update-all
Ctrl+0 set glsl-shader ""
Ctrl+1 set glsl-shader "~~/shaders/SSimDownscaler.glsl;~~/shaders/ravu-lite-r4.hook;~~/shaders/ravu-zoom-r4-chroma.hook"
Ctrl+2 set glsl-shader "~~/shaders/Anime4K_Upscale_CNN_x2_L.glsl"