# --- SUBTITLES ---
sub-font-size=60
sub-bold=yes
sub-color='#e8f3b6'

# --- STREAMING & BUFFERING ---
cache=yes
# Set forward buffer to 1GB (allows ~10-15 mins of 1080p to sit in RAM)
demuxer-max-bytes=1024MiB
# Set backward buffer (allows instant seeking back)
demuxer-max-back-bytes=512MiB
# Try to buffer 10 minutes (600 seconds) ahead
demuxer-readahead-secs=600
# Force mpv to wait until the cache is at least 10% full before starting
cache-pause-initial=yes
# If the cache runs dry, pause and wait for it to refill instead of stuttering
cache-pause=yes
autocreate-playlist=filter


# --- PERFORMANCE (LINUX) ---
# Use hardware acceleration to keep CPU usage low
hwdec=auto-safe
# High-quality video output
vo=gpu-next

# --- CONVENIENCE ---
save-position-on-quit=yes

# --- OSC ---
osc=no

# --- VIDEO QUALITY ---
scale=spline36
dscale=mitchell
cscale=bilinear
video-sync=display-resample
interpolation=yes

# --- SCREENSHOTS ---
screenshot-format=png
screenshot-png-compression=1
screenshot-directory=~/.local/share/mpv/screenshots

# --- AUDIO ---
volume=100
volume-max=150
alang=jpn,jp,ko,kor,en,eng

# --- SUBTITLE LANGUAGE ---
slang=vi,vie,en,eng
sub-auto=fuzzy

# --- WINDOW ---
keep-open=yes
force-window=immediate
autofit=80%x80%
geometry=50%:50%

# --- SEEKBAR ---
hr-seek=yes
hr-seek-framedrop=no

# --- DEBANDING ---
deband=yes

# Optimized shaders for higher-end GPU: Mode A (HQ)
# glsl-shaders="~~/shaders/Anime4K_Clamp_Highlights.glsl:~~/shaders/Anime4K_Restore_CNN_VL.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_VL.glsl:~~/shaders/Anime4K_AutoDownscalePre_x2.glsl:~~/shaders/Anime4K_AutoDownscalePre_x4.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_M.glsl"
