entryPoints:
  web:
    address: ":80"

providers:
  file:
    directory: /traefik.d
    watch: true
  docker:
    watch: true
    exposedByDefault: false
    endpoint: "unix:///var/run/docker.sock"
    network: "web"

api:
  dashboard: true
  insecure: true

log:
  level: DEBUG
