entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  file:
    directory: /traefik.d
    watch: true
  docker:
    watch: true
    exposedByDefault: false
    endpoint: "unix:///var/run/docker.sock"
    network: "traefik_net"

tls:
  certificates:
    - certFile: "./certs/inertia.test.pem"
      keyFile: "./certs/inertia.test-key.pem"
    - certFile: "./certs/erp.langmaster.test.pem"
      keyFile: "./certs/erp.langmaster.test-key.pem"
    - certFile: "./certs/cafemom.test.pem"
      keyFile: "./certs/cafemom.test-key.pem"
    - certFile: "./certs/langmaster.edu.pem"
      keyFile: "./certs/langmaster.edu-key.pem"
    - certFile: "./certs/erp.hbr.test.pem"
      keyFile: "./certs/erp.hbr.test-key.pem"

api:
  dashboard: true
  insecure: true

http:
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: "https"

log:
  level: DEBUG
