cursor #dee2ee
cursor_text_color #c1c7d2

foreground            #dee2ee
background            #0e141c
selection_foreground  #262f4d
selection_background  #bcc5eb
url_color             #a3c9ff

color0   #0e141c
color1   #ff729b
color2   #7fff91
color3   #fff772
color4   #89b4f2
color5   #274876
color6   #a3c9ff
color7   #eff6ff
color8   #999ea5
color9   #ff9fbb
color10  #a5ffb2
color11  #fffaa5
color12  #b0d1ff
color13  #bed9ff
color14  #d5e6ff
color15  #f8fbff
